version: "3"
services:
  nginx:
    image: nginx:1.25.0
    ports:
      - 8080:80
    volumes:
      - ./www/html:/var/www/html
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - app
  app:
    build:
      context: ./docker/app
    volumes:
      - ./www/html:/var/www/html
  mysql:
    build:
      context: "docker/mysql/"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_HOST=mysql
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=Asia/Tokyo
    volumes:
      - "./docker/mysql/storage/:/var/lib/mysql"
      - "./docker/mysql/initdb/:/docker-entrypoint-initdb.d"
      - "./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf"
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8081:80
    environment:
      - PMA_HOST=mysql
      - PMA_USER=${MYSQL_USER}
      - PMA_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
      - mysql